version: '3'
services:
  frontend:
    container_name: techio_client
    build:
      context: ./client
      dockerfile: Dockerfile
    image: dattran1232003/techio_client
    ports:
      - 3000:3000
    volumes:
      - ./client:/usr/src/client

  backend:
    container_name: techio_server
    build:
      context: ./
      dockerfile: Dockerfile
    image: dattran1232003/techio_server
    ports:
      - 5000:5000
    volumes:
      - ./server:/usr/src/server
